### PR TITLE
configurable retransmit timeout (IDFGH-5831)

### PR DESCRIPTION
**Pull request by umer-ilyas**
sometime user want to configure retransmit timeout due to network or other requirement

### CODE REVIEW

**Review by david-cermak — CHANGES_REQUESTED** [review]
LGTM in general, but suggest removing the `...update_timeout()` API, just to keep it simple. We already have too many config options and no interface to set them separately.

Runtime configuration should be possible by means of
* `esp_mqtt_set_config()`
which updates only non-zero fields, so applicable to all config options, essentially.

**Comment by david-cermak** [comment]
@umer-ilyas Thanks for posting this PR, indeed useful to have  retransmission configurable.

**Comment by umer-ilyas** [comment]
@david-cermak it is possible to configure the `message_retransmit_timeout` in `esp_mqtt_set_config()`
https://github.com/espressif/esp-mqtt/pull/199/files#diff-ed41b90c439eecb3e26ddb113b6f02d09acba8798161ca09ed398ab8ab043244R368-R372

**Review by david-cermak — APPROVED** [review]
Thanks for the quick update!

**Comment by david-cermak** [comment]
Thanks for the contribution, merged as https://github.com/espressif/esp-mqtt/commit/1b009c840b78a14f59b6ada70d36aca9ad6303f0

**Pull request closed without merging**
