### PR TITLE
Add SSL mutual authentication support

### PR DESCRIPTION
**Pull request by rbino**

### CODE REVIEW

**Comment by tuanpmt** [comment]
Hi @rbino 

Because we have `cert_pem` attribute for the configuration, I think we should add `key_pem` instead of `client_cert_pem` and `client_key_pem`. Also, `transport_ssl_set_key_data` is enough

Thanks

**Comment by rbino** [comment]
Hi,
the existing `cert` and the new `client_cert` are two separate things (one is the one served from the server, the other is the one that the client sends for authentication) so I'm not sure what you mean when you say "I think we should add key_pem instead of client_cert_pem and client_key_pem".

Can you please clarify? I may be missing something.

**Comment by rbino** [comment]
@tuanpmt did you have time to check my questions above?

**Comment by tuanpmt** [comment]
Hi @rbino 

You are right. I have a little confusion as I only think of authentication from the server.  Currently, the internal team is integrating this library into the IDF with some changes. I will send to the internal team review and integrate this useful feature before being synced back to GitHub.

Thanks

**Comment by david-cermak** [comment]
Hi @rbino, 
Thanks for implementing this useful feature. We've decided to merge it to master first before including to IDF.

**Pull request merged**
