### PR TITLE
Reliability improvements. (IDFGH-887)

### PR DESCRIPTION
**Pull request by oldgreen**
For more details please see the individual commit messages.

### CODE REVIEW

**Comment by tuanpmt** [comment]
@oldgreen 

Could you please help update master and reduce the MR?

Thanks

**Comment by oldgreen** [comment]
@tuanpmt 

I'll have a look later this week.

**Comment by oldgreen** [comment]
I won't be able to get to this in the next 3 weeks, but it's still on my todo list.

**Comment by projectgus** [comment]
Hi @oldgreen ,

Is there still any updates in your PR that you think should be applied to esp-mqtt?

Thanks,

Angus

**Comment by oldgreen** [comment]
@projectgus I don't know, but it should be fairly easy to review the individual commits and compare them to current master. Feel free to use anything you like, I am not going to work on this anytime soon.

**Comment by david-cermak** [comment]
Thanks @oldgreen for your help in improving the stability of this library. Added some bits of the fixes you proposed in https://github.com/espressif/esp-mqtt/commit/6f1fc3785af8cc7765f78dd93f09aeb0109cd2b7 some time ago but forgot to mention here. Closing it now. Thanks again for your contribution!

**Pull request closed without merging**
